### ISSUE TITLE
How to achieve model performance that is quite as good as in the paper while debugging the code?

### ISSUE THREAD

**Issue by CAG-kong** [fitzpchao/BANDON#2]
After delving into your recent research papers, I was deeply impressed by the remarkable contributions you have made to the field. The moment your source code became open-source, I eagerly embarked on a journey to learn from it and attempt to reproduce the exceptional model performance described in the papers. However, during the process of debugging and fine-tuning the code, I encountered significant discrepancies in the model's performance compared to the reported results. I am reaching out with a sincere and humble request for guidance and assistance. I think there might be subtle intricacies or specific procedures that I might have overlooked while trying to reproduce your work. Therefore, I was hoping you could give me some advice, tips or clarification about the code implementation or any potential issues I should be aware of, thank you very much!

**Comment by fitzpchao** [comment]
Tell me your experiment setting and the test results. If it is convenient, please give me your communication method or email address, we will discuss further.

**Comment by fitzpchao** [comment]
> After delving into your recent research papers, I was deeply impressed by the remarkable contributions you have made to the field. The moment your source code became open-source, I eagerly embarked on a journey to learn from it and attempt to reproduce the exceptional model performance described in the papers. However, during the process of debugging and fine-tuning the code, I encountered significant discrepancies in the model's performance compared to the reported results. I am reaching out with a sincere and humble request for guidance and assistance. I think there might be subtle intricacies or specific procedures that I might have overlooked while trying to reproduce your work. Therefore, I was hoping you could give me some advice, tips or clarification about the code implementation or any potential issues I should be aware of, thank you very much!

Tell me your experiment setting and the test results. If it is convenient, please give me your communication method or email address, we will discuss further.

**Comment by fitzpchao** [comment]
Tell me your experiment setting and the test results. If it is convenient, please give me your communication method or email address, we will discuss further.
