### ISSUE TITLE
你好，前辈，我想问一下关于真值的问题

### ISSUE THREAD

**Issue by wangqingl** [fitzpchao/BANDON#6]
您的数据集一共有四种真值，ST-offsets，Seg，BI-flows，Final change mask这四种，我想问一下，您如果想对比建筑物之间是否发生变化，是不是只需要Seg，BI-flows，Final change mask这三种就可以了，是不是就不需要ST-offsets也可以了，因为我们找到对应建筑物的目的已经到了不是吗？期待您的回复谢谢

**Comment by fitzpchao** [comment]
是的

**Comment by wangqingl** [comment]
好的，感谢您，我明白了
