### ISSUE TITLE
你好，我想问一下关于BT-flow的标签格式问题

### ISSUE THREAD

**Issue by wangqingl** [fitzpchao/BANDON#7]
你好前辈，我看您的BT-flow标签里面是.tif格式的图像，32位深度的图，我想问一下，怎么解析这个图像里面的信息呢，因为我的数据集也想制作一下这种偏移的标签数据，可以给我一些建议吗，谢谢

**Comment by wangqingl** [comment]
你好前辈，我看您的BT-flow标签里面是.tif格式的图像，32位深度的图，我想问一下，怎么解析这个图像里面的信息呢，因为我的数据集也想制作一下这种偏移的标签数据，可以给我一些建议吗，谢谢

**Comment by fitzpchao** [comment]
模型在处理光流数据的时候正常使用tiff库读取，比如gdal，rasterio等。可视化分析数据时，需要根据光流方向和强度赋予特定颜色及其深度。

**Comment by wangqingl** [comment]
> 模型在处理光流数据的时候正常使用tiff库读取，比如gdal，rasterio等。可视化分析数据时，需要根据光流方向和强度赋予特定颜色及其深度。

![image](https://github.com/fitzpchao/BANDON/assets/102707449/0cc740fb-eb83-47e3-a193-6959a1ff949c)
好的谢谢，我想问一下，您的train数据集里面的这个文件夹里面是什么数据呀

**Comment by fitzpchao** [comment]
建筑物变化检测0/1标签，255是ignore的区域

**Comment by wangqingl** [comment]
> 建筑物变化检测0/1标签，255是ignore的区域

哦哦好的，谢谢你。还有个问题就是，您在制作BI-flow时，是通过已经标注过的两张图的ST-flow计算得到的吗。我可以通过标注两个物体的顶面来得到这个BI-flow嘛。

**Comment by fitzpchao** [comment]
是的。我是用算法去匹配上每个轮廓的，因为这个数据在刚开始标注的时候没有计划做变化检测。如果从头开始搞，我建议你在标注的时候就人工判断是否为同一个屋顶，然后赋予这两个polygon相同的id属性。

**Comment by wangqingl** [comment]
> 是的。我是用算法去匹配上每个轮廓的，因为这个数据在刚开始标注的时候没有计划做变化检测。如果从头开始搞，我建议你在标注的时候就人工判断是否为同一个屋顶，然后赋予这两个polygon相同的id属性。

好的，谢谢您的指导。我还有个疑问就是，为什么我看您的原图是2048大小，但是BI-flow标签是256大小呢
![image](https://github.com/fitzpchao/BANDON/assets/102707449/7a4ae758-c4b8-4334-b9a9-4e45892a94c7)
![image](https://github.com/fitzpchao/BANDON/assets/102707449/e878010c-89d9-4c54-af18-52baf29dc887)

**Comment by fitzpchao** [comment]
我们发现光流不需要太高分辨率，为了节省模型训练内存和存储空间，就把2048放缩了

**Comment by wangqingl** [comment]
> 我们发现光流不需要太高分辨率，为了节省模型训练内存和存储空间，就把2048放缩了

这样，好的，谢谢您的回答
