### ISSUE TITLE
关于   代码里面MTGCDNet.py里面  num_classes 问题

### ISSUE THREAD

**Issue by HHLiufighting** [fitzpchao/BANDON#8]
您好，我看的您的代码里面MTGCDNet.py里面，num_classes分别是2，3，3，10，10，10个类别。2指的是最终的变化图，3指的是分割结果图，10是ST-flow和BI-flow图，是这样吗？那么您是用的分类的方法去做的偏移嘛。我这样理解对吗
![f1686c66a87964ddd21c817c5dd6ed2](https://github.com/fitzpchao/BANDON/assets/114455501/baa0ebf0-3552-402b-b4e0-c4e56c4c163c)

**Comment by fitzpchao** [comment]
是的

**Comment by HHLiufighting** [comment]
> 是的
好的谢谢，您在论文里面说回归任务要比分类更难学习，您之前做实验的时候，关于回归的方法试验效果比较差吗

**Comment by fitzpchao** [comment]
嗯嗯。 回归的方法会导致两个问题：1.训练时间增加 2.目标主任务变化检测的性能会受影响性能下降

**Comment by HHLiufighting** [comment]
> 嗯嗯。 回归的方法会导致两个问题：1.训练时间增加 2.目标主任务变化检测的性能会受影响性能下降

那您偏移的标签只有角度  没有位移吗

**Comment by fitzpchao** [comment]
有的，算法层面是分为x,y两个方向去预测的位移，但是实际实现的时候，为了模型简单。  我在训练的时候只预测一个x方向的位移，因为图像随机旋转，xy并没有区别。
