### ISSUE TITLE
请问一下关于前后两张图像偏移的标签问题

### ISSUE THREAD

**Issue by wangqingl** [fitzpchao/BANDON#9]
您好，我使用ps软件打开了.tif格式的标签，但是里面显示的部分有些地方有一些歧义，如L81_00639_783959这张图，打开之后有三个不同的通道，里面显示了不同的内容
下面分别是三个不同通道的图像，这个是什么问题呢
![image](https://github.com/fitzpchao/BANDON/assets/102707449/89ae61f1-e059-49f3-af0a-ba0a201026b5)
![image](https://github.com/fitzpchao/BANDON/assets/102707449/d4ac3318-c462-49d2-9eb4-25c9357af10c)
![image](https://github.com/fitzpchao/BANDON/assets/102707449/16509e67-8d27-4463-b493-8e58e76312c5)

**Comment by fitzpchao** [comment]
分别是x偏移量，y偏移量，ignore的区域（change 区域）

**Comment by fitzpchao** [comment]
如果需要深入交流，可以加我QQ 897090697

**Comment by wangqingl** [comment]
> 如果需要深入交流，可以加我QQ 897090697


> 分别是x偏移量，y偏移量，ignore的区域（change 区域）

好的谢谢，我搜索了您的QQ，但是好像搜索不到，提示可能设置了无法搜索，可以麻烦加一下我不，2448989281，
